name: Docker Build and Publish with Buildx (Ascend)

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    publish-base:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                branch: [
                    "featured/base",
                    "jupyter/base",
                ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Change BASE_IMAGE to Ascend
              run: |
                  make set_type TYPE=ascend

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install vcs
              run: |
                sudo apt-get install -y python3-pip && pip3 install vcstool

            - name: Publish ${{ matrix.branch }}
              run: |
                  export BRANCH=${{ matrix.branch }} && make publishx
              continue-on-error: true

    publish-extras:
        runs-on: ubuntu-latest
        needs: publish-base
        strategy:
            matrix:
                branch: [
                    "featured/speit-ascendai",
                    "jupyter/speit-ascendai"
                ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Change BASE_IMAGE to Ascend
              run: |
                  make set_type TYPE=ascend

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install vcs
              run: |
                sudo apt-get install -y python3-pip && pip3 install vcstool

            - name: Publish ${{ matrix.branch }}
              run: |
                  export BRANCH=${{ matrix.branch }} && make publishx
              continue-on-error: true
