name: Docker Build and Publish with Buildx (Ascend)

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    publish-base:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                branch: [
                    "featured/base",
                    "coder/base",
                    "jupyter/base",
                ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Change BASE_IMAGE to Ascend
              run: |
                  sed -i 's|^BASE_IMAGE=.*$|BASE_IMAGE=ascendai/cann:8.3.rc2-910b-ubuntu22.04-py3.11|g' .dockerargs

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install vcs
              run: |
                sudo apt-get install -y python3-pip && pip3 install vcstool

            - name: Publish ${{ matrix.branch }}
              env:
                  TAG_POSTFIX: "-ascend"
              run: |
                  export BRANCH=${{ matrix.branch }} && make publishx
              continue-on-error: true

    publish-extras:
        runs-on: ubuntu-latest
        needs: publish-base
        strategy:
            matrix:
                branch: [
                    "featured/speit",
                    "featured/dind",
                    "featured/ros2",
                    "coder/lite",
                    "jupyter/speit"
                ]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # - name: Change BASE_IMAGE to Ascend
            #   run: |
            #       sed -i 's|^BASE_IMAGE=.*$|BASE_IMAGE=ascendai/cann:8.3.rc2-910b-ubuntu22.04-py3.11|g' .dockerargs

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install vcs
              run: |
                sudo apt-get install -y python3-pip && pip3 install vcstool

            - name: Publish ${{ matrix.branch }}
              env:
                  TAG_POSTFIX: "-ascend"
              run: |
                  export BRANCH=${{ matrix.branch }} && make publishx
              continue-on-error: true
